### ISSUE TITLE
Выход в свет

### ISSUE THREAD

**Issue by ivan-smirnyagin-1** [mnoskov/commerce#1]
Здравствуйте. Когда ожидать окончательный выход вашего модуля в свет ? ) поставил текущие решение что есть, очень все интересно сделано и удобно!

**Comment by mnoskov** [comment]
Может месяц-два, пока не знаю. Какой функционал вам нужен?

**Comment by ivan-smirnyagin-1** [comment]
Например, красивую статистику, в виде диаграммы продаж. Либо как вариант вот такое (скрин приложил). Виджет дополнительный вывести такой на рабочем столе в админке evolution. 
![2018-10-25_11-48-54](https://user-images.githubusercontent.com/24613445/47481123-17033380-d84c-11e8-9198-e3727c28ba55.png)
