### ISSUE TITLE
« Evolution CMS Parse Error » syntax error, unexpected '}', expecting ')'

### ISSUE THREAD

**Issue by Fedor858** [mnoskov/commerce#113]
После установки плагина система  падает полностью вот   с такой ошибкой,версии  пхп разные,от 7,2 до 8,версии  evo  3 и 1,4,на  1,4 вывод баги  Parse error: syntax error, unexpected '}', expecting ')' in C:\OpenServer\domains\evo.loc\manager\includes\document.parser.class.inc.php(1921) : eval()'d code on line 42,ставил и вручную и с extra.
<a href="https://ibb.co/P9HWPJK"><img src="https://i.ibb.co/0Fb961T/Whats-App-Image-2022-01-08-at-10-51-42.jpg" alt="Whats-App-Image-2022-01-08-at-10-51-42" border="0"></a>

**Comment by mnoskov** [comment]
https://github.com/mnoskov/commerce/pull/111
