### ISSUE TITLE
Language correction

### ISSUE THREAD

**Issue by mnoskov** [mnoskov/commerce#13]
@fourroses666
Hello! Could you please correct language strings here - https://github.com/mnoskov/commerce/tree/master/assets/plugins/commerce/lang/nederlands-utf8
When you have time, ofcourse :)

**Comment by fourroses666** [comment]
Sorry didn't see this.

**Comment by fourroses666** [comment]
These 2 files are changed. Hope you don't mind I did it like this.
[nederlands-utf8.zip](https://github.com/mnoskov/commerce/files/3614152/nederlands-utf8.zip)

**Comment by mnoskov** [comment]
Thanx!
