### ISSUE TITLE
php8.1 Deprecated: trim(): Passing null to parameter

### ISSUE THREAD

**Issue by webber12** [mnoskov/commerce#138]
1× | PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in Plugin OnWebPageInit[Commerce]:103
1× | PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in Plugin OnWebPageInit[Commerce]:145

Сыпет предупреждения.

**Comment by Pathologic** [comment]
Где это? В плагине нет таких строк.

**Comment by webber12** [comment]
В том и вопрос - строк нет, а ошибка есть :)

В общем, методом ненаучного тыка обнаружил что эти строки находятся в core/src/Parser.php 
https://github.com/evocms-community/evolution/blob/3.x/core/src/Parser.php#L103
https://github.com/evocms-community/evolution/blob/3.x/core/src/Parser.php#L145

Именно туда и прилетают нулевые значения для trim. Сделал им приписку ?: '' и ошибка ушла.
