### ISSUE TITLE
PHP 8+, Evo 3 невозможно дописать markup к способу доставки

### ISSUE THREAD

**Issue by sashabeep** [mnoskov/commerce#140]
Я создаю доставку
```php
$title = 'Самовывоз';
switch ($modx->Event->name) {
    case 'OnRegisterDelivery': {
        $params['rows']['pickup'] = [
            'title' => $title,
        ];
        break;
    }
}
```

Потом плагин на событие **OnBeforeOrderAddonsRender** который добавляет оформление 
```php
$params['delivery']['pickup']['markup'] .= '....
```
И получаю ошибку
```
Error : Undefined array key "markup"
Warning: Undefined array key "markup" in /home/.../core/src/Core.php(1851) : eval()'d code on line 5
```

Если сделать дамп **$params** в плагине, то видно, что у способов оплат есть пустой ключ markup, а у доставок - нет
```
 [payments] => Array ( [billpayment] => Array ( [title] => Оплата по счету [markup] => ) )
 [delivery] => Array ( [pickup] => Array ( [title] => Самовывоз ) [transp] => Array ( [title] => Доставка транспортными компаниями ) ) 
```

Я добавил пустой ключ markup в плагины доставки и теперь всё работает. Может, его надо добавить так же, как у оплат? Не могу найти где. На php 7.4 объявлять пустой ключ не требовалось.

**Comment by Pathologic** [comment]
А проблема в чем?

**Comment by Pathologic** [comment]
Теперь надо добавлять. Или не писать .=
