### ISSUE TITLE
Модульность событий и их перехват

### ISSUE THREAD

**Issue by sazanof** [mnoskov/commerce#17]
Добрый день. Прошу прощения сразу за непонятный заголовок, сейчас поясню.
Вопрос касаемо js и того, как не меняя конкретно Ваш исходный код перехватывать события.
В самом файле commerce.js объявление объекта, его вызов, и ещё serialize
У меня была необходимость скажем по добавлению/редактированию/удалению из/ в корзину делать определенные изменения dom, выводить, скажем корзину в модалке fancybox, использовать noty.js
Для этого я использовал mutationObserver, чтобы отслеживать изменения , которые коммерс вносит в dom. Способ костыльный, однако у меня получилось. 
Только что вспомнил, что по сути можно в своем скрипте назначать второй onclick на тот же элемент, но будет не совсем то, что нужно. Понимаю, что определенная задача требует определенного вмешательства в код, но хотелось бы до инициализации переопределять методы объекта commerce или использовать колбэки. 
Это конечно больше к js вопросы, однако спрошу: будет ли такая возможность реализована? 
Сейчас пишу проект, и если не против, могу немного подкорректировать или добавить эту логику для последующей обработки "своих" скриптов по событиям коммерс. 

Сорян, если ничего не понятно)

**Comment by sazanof** [comment]
Сейчас смотрю код и понимаю, что там же вроде как есть уже евенты. 
Надо попробовать будут ли они работать в коде  потипу Commerce.on(event,function(data){})

**Comment by mnoskov** [comment]
https://github.com/evolution-cms/docs/blob/master/ru/04_%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/Commerce/20_%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B5_%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D1%8F.md

**Comment by sazanof** [comment]
Все более чем понятно. Спасибо.
