### ISSUE TITLE
Evo 2.0, контроллеры и api=1

### ISSUE THREAD

**Issue by sazanof** [mnoskov/commerce#18]
Добрый дееь. 
При использовании сниппета Cart в любом  контроллере (evo 2.0) с параметром api=1 возвращается только массив с товарами в корзине. 

Есть ли возможность добавить чтобы возвращались и общие данные те же, что поступают в плейсхолдеры outerTpl и другие: hash, count, total_price? 
Могу ошибаться с названиями, пишу с телефона. Если хэш корзины и общее кол-во позиций получить можно быстро, то для формирования общей цены придется гонять массив. 
Возможно я не прав и такое уже есть в реализации, тогда просто закрывайте с комментов:читай доку)
Спасибо, что дочитали.

**Comment by mnoskov** [comment]
С api не тестировал, логично что там только товары. Добавлю это в планы

**Comment by mnoskov** [comment]
Для получения доп.информации также нужно добавить параметр JSONformat = new
