### ISSUE TITLE
Can it already be used without payment

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/commerce#2]
Hi M. Noskov, 

Really like your stuff.

I wonder, is this possible to use already?
I don't need a payment (yet), just a checkout form send to an emailaddress and the products needs to have a "add to basket" and a summary of the costs.

**Comment by mnoskov** [comment]
Hi!
I don't recomment to use this on production.

**Comment by fourroses666** [comment]
Oke thanks, will have do testing when have some spare time.

**Comment by fourroses666** [comment]
It kills my website after installing commerce with Packagemanager!
Tried on 2 test domains.

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
```

**Comment by mnoskov** [comment]
Don't know about Packagemanager, I installed this through Extras.
Can you give me access to this site? For mail@mnoskov.ru

**Comment by fourroses666** [comment]
I have mailed you but don't think its possible to do/check allot because of the server error.

**Comment by mnoskov** [comment]
Which version of cms? PHP version? Sholud be 1.4.7 and 5.6. You can disable plugin Commerce in database, then clear cache.

**Comment by fourroses666** [comment]
PHP 7.1.26
EVO 1.4.8

Ok disable probably will fix it.

**Comment by fourroses666** [comment]
Seems to be the CommerceInstall, probably the install with PackageManager does not go correct..
When I disable that the manager gets available again.

**Comment by fourroses666** [comment]
The installer doesn't get disabled while it looks like everything is installed. Maybe thats the problem?

**Comment by mnoskov** [comment]
Installer should run on page load and then remove himself.

**Comment by fourroses666** [comment]
Don't know why that doesn't work.

**Comment by mnoskov** [comment]
Found sql error in installer, fixed it. Just tested with Packagemanager, installed normally

**Comment by mnoskov** [comment]
I just realized that the plugin doesn't have your language. This can cause an error as well.

**Comment by fourroses666** [comment]
Good find :)

I can translate. 
Long time I've used Github Desktop to make a pull request thow.
I will try.

**Comment by fourroses666** [comment]
When I add; `[!Order ... !]` I get Internal Server Error.
Don't know if my Pull request had a wrong foldername or its something else.
Not sure if `nederlands-UTF8` is correct. The Module shows nothing, nothing loaded.

I'm oke with building a very simple demo for it in the future on bulma.io

**Comment by fourroses666** [comment]
And the folder for English needs to be: english and not english-UTF8
But I don't know how to create a new pull request :-(

Maybe you can accept the pullrequest and rename the folders?

**Comment by fourroses666** [comment]
I think its done OKE now :)

**Comment by fourroses666** [comment]
There are no default chunks `tpl-x` installed. Don't know if thats correct.
Also I noticed `["Uplift","Assembling"]` which maybe isn't added to the lang files.
I probably will need some documentation to play with it and test it.
