### ISSUE TITLE
Транзакции в OrdersProcessor

### ISSUE THREAD

**Issue by Pathologic** [mnoskov/commerce#25]
Судя по закомментированному коду предполагалось их использовать - сейчас препятствий нет, в dbapi обеих веток есть поддержка.

**Comment by mnoskov** [comment]
Я сейчас плохо помню, но вроде на 2.0.1 и пробовал, все ошибки перехватывал стандартный обработчик.

**Comment by Pathologic** [comment]
Ну, если там чего-то не хватает, так можно допилить. Я методы для транзакций добавлял чтобы мои комментарии работали, вроде не было проблем.

**Comment by mnoskov** [comment]
Не пойму, как их использовать, какой код должен быть.

```php
$db = $modx->db;

if ($db->begin(0, 'Commerce')) {
	try {
		$db->insert([
			'id'   => 1, // duplicated primary key
			// missed fields
		], $modx->getFullTablename('commerce_order_history'));

		if (!$db->commit()) {
			echo 'thrown!';
			throw new Exception('Cannot commit transaction!');
		}
	} catch (Exception $e) {
		echo 'catched!';
		$db->rollback();
	}
}
```

Молча проглатывается, ни ошибки, ни записи.

**Comment by Pathologic** [comment]
Код работает правильно, просто в нем неправильная логика :cat: 
```
$db = $modx->db;

if ($db->begin()) {
	try {
                $order_id = $db->insert(...);
                $result = ... сохраняем товары, если не получилось, тогда и заказ создавать не будем
		if (!$result || !$db->commit()) {
			echo 'thrown!';
			throw new Exception('Cannot commit transaction!');
		}
	} catch (Exception $e) {
		echo 'catched!';
		$db->rollback();
	}
}
```

**Comment by mnoskov** [comment]
https://github.com/mnoskov/commerce/commit/5f8e8c6d7c43e36d5fe1855ef3e97b9b57116817
