### ISSUE TITLE
Wishlist missing currency

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/commerce#26]
Minor issue. When I add the price on a product with a comma like 89,95 the currency won't show on the Wishlist page. When I remove the comma like 89 or use 89.95 in the price field the currency shows.

`[!Wishlist!]`

![wishlist](https://user-images.githubusercontent.com/523389/76607497-53ecca80-6514-11ea-891d-9233d03ef048.jpg)

**Comment by fourroses666** [comment]
Don't know why but its still not working.

**Comment by fourroses666** [comment]
Only product that shows the currency is the one where I have price TV: 21 without `,xx` behind it.

**Comment by mnoskov** [comment]
Is it only one currency? Can you show currency settings and product admin page with price?

**Comment by fourroses666** [comment]
Its only currency which is missing when the price TV has a **,** in it.

Example:
Price TV: _21,95_ or _21,00_ won't show the currency on the wishlist page.
Price TV: _21_ will show the currency (and add the 00 ->  21,00)

[!Order!] Does show it correct, price and currency. 
So its only on the Wishlist.

![settings-valuta](https://user-images.githubusercontent.com/523389/76989042-08885100-6946-11ea-8b52-91f158b74602.jpg)
