### ISSUE TITLE
В сниппет Order нужно добавить параметр ignoreMailerResult

### ISSUE THREAD

**Issue by Pathologic** [mnoskov/commerce#30]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/ru/050_%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0_%D0%BF%D0%B8%D1%81%D0%B5%D0%BC.md#ignoremailerresult

**Comment by mnoskov** [comment]
А зачем?

**Comment by Pathologic** [comment]
Смысла нет отслеживать, отправилась почта или не отправилась, главное сохранить заказ в базе.

**Comment by mnoskov** [comment]
Думаю, это можно в вызов сниппет Order добавить, если надо
