### ISSUE TITLE
При установке отсюда не создались статусы заказов

### ISSUE THREAD

**Issue by sashabeep** [mnoskov/commerce#32]
Только что установил через zip. Список статусов пустой.

~При отправке заказа в ответ на ajax приходит главная страница с пустым местом там, где стоит вызов сниппета вместо json со статусом... Что я еще мог пропустить?~

**Comment by mnoskov** [comment]
Какая весрия php, evo, mysql?

**Comment by sashabeep** [comment]
2.0.2, 7.4.1
В-общем, скопировал статусы с другого сайта.
Скорее всего, это был глюк. Был включен свой плагин на onpagenotfound выше commerce, поэтому заказы не прилетали, может, и плагин установки так же не смог отработать

**Comment by sashabeep** [comment]
Только что на 1.4.11 php 7.4.1 также не создались статусы. Скопировал с другого сайта. Также Не выставляется статус "Оплачен" при тестовой оплате через robokassa
