### ISSUE TITLE
Оформление в коде формы редиректа на оплату

### ISSUE THREAD

**Issue by sashabeep** [mnoskov/commerce#35]
При длинном чеке его содержимое не умещается в длину get-запроса в https://github.com/mnoskov/commerce/blob/master/assets/plugins/commerce/templates/front/payment_form.tpl

Возможно, стоит пересмотреть метод отправки или сделать его переключаемым.
Отловлено на длинном чеке с оплатой в робокассе. Весь чек не помещается в количество символов get-запроса, платеж прерывается

**Comment by mnoskov** [comment]
https://github.com/mnoskov/commerce/commit/a66aa0155ec57df51d3b62993580c1566ed1ad54 https://github.com/mnoskov/commerce-payment-robokassa/commit/2608730a6f45c396e31f99f6d8ab4dddb06835f3
