### ISSUE TITLE
Не разворачивается дерево при добавлении товара в редактировании заказа

### ISSUE THREAD

**Issue by mnoskov** [mnoskov/commerce#42]
Переделать commerce/module action с события OnPageNotFound на отдельный скрипт, чтобы была возможность определить IN_MANAGER_MODE до включения движка.

**Comment by Pathologic** [comment]
Не в этом дело, у тебя здесь https://github.com/mnoskov/commerce/blob/master/assets/plugins/commerce/src/Commerce.php#L434 ожидается $_POST['route'], а в реальности это $_POST['type']. Такая же путаница была в dashboard.

**Comment by mnoskov** [comment]
Точно, спасибо.
