### ISSUE TITLE
Valuta symbol before price

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/commerce#5]
How can I use module.left_symbol ?

Can find it in the Plugin or module to change it to be before the valuta.

**Comment by mnoskov** [comment]
It can be changed on Currencies page
![2019-02-04_17-47-20](https://user-images.githubusercontent.com/8789957/52209207-0596e200-28a5-11e9-9626-e091374fa36f.png)

**Comment by fourroses666** [comment]
Oh wow didn't even see that! Nice!

**Comment by fourroses666** [comment]
Just a notice;

- You can't open multiple Tabs from the top navigation when you have [(global_tabs)] on. 
- The icon for Orders is configuration icon but would the cart icon be better?
fa-cog --> fa-shopping-cart

**Comment by 0test** [comment]
Where to download the module "Currencies"?
