### ISSUE TITLE
Возможность задать шаблон формы заказа при пустой корзине

### ISSUE THREAD

**Issue by mnoskov** [mnoskov/commerce#56]

**Comment by Pathologic** [comment]
Тогда неплохо было бы и возможность редиректа сделать. По умолчанию можно редиректить на cart_page_id.

**Comment by mnoskov** [comment]
Редирект с формы если пустая корзина?

**Comment by Pathologic** [comment]
Да, потому что если корзина пустая, то какой смысл показывать сообщение об этом на двух страницах. А редиректить по умолчанию, думаю, не нужно - большинство не делает отдельную страницу для заказа. 
Есть еще один косячок с формой заказа и корзиной - если из корзины товары поудалять все, то форма заказа останется.

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/docs/blob/master/ru/04_%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/Commerce/05_%D0%9E%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0.md
