### ISSUE TITLE
TAX + Wishlist

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/commerce#6]
Can find a Wishlist template.
Are you planning to build-in TAX?

**Comment by mnoskov** [comment]
Simple wishlist snippet:
```php
if (!empty($modx->commerce)) {
    $items = ci()->carts->getCart('wishlist')->getItems();

    return $modx->runSnippet('DocLister', array_merge($params, [
        'idType'    => 'documents',
        'documents' => array_unique(array_column($items, 'id')),
    ]));
}
```

**Comment by mnoskov** [comment]
If you mean tax, it can be implemented by simple plugin:
```php
if ($modx->Event->name == 'OnCollectSubtotals') {
    $params['rows']['vat'] = [
        'title' => 'VAT',
        'price' => $params['total'] * 0.20,
    ];
}

```

**Comment by fourroses666** [comment]
The wishlist don't work on my testsite when adding the snippet and add to wichlist by;
`<a href="#" data-commerce-action="add" data-id="[*id*]" data-instance="wishlist">Add to wishlist</a>`

**Comment by mnoskov** [comment]
Check script "commerce.js" must be included on page.

**Comment by fourroses666** [comment]
Oke, that script wasn't added to the site.
But its still not working.
And clicking on "add product" it adds 2 items.

**Comment by mnoskov** [comment]
Can you share site address?

**Comment by mnoskov** [comment]
Script appended twice - in head (manually), and at the end of the page (by plugin)

**Comment by fourroses666** [comment]
Ah didn't see that :-) But add to wishlist still does nothing.

**Comment by mnoskov** [comment]
Yes, dont't know why, but cookie with list not created.

**Comment by fourroses666** [comment]
Oke

**Comment by mnoskov** [comment]
Can you replace this file?
https://raw.githubusercontent.com/mnoskov/commerce/master/assets/plugins/commerce/src/Carts/CookiesCartStore.php
Maybe it helps

**Comment by fourroses666** [comment]
Hi, I have replaced it but still see no cookie being stored.

**Comment by mnoskov** [comment]
Ok, I found bug, this commit should fix it - https://github.com/mnoskov/commerce/commit/6f3c6aaca00882d6053a865193b5341a3dc6fd6e.
Can you patch files from commit?

**Comment by fourroses666** [comment]
The 2 files are replaced, don't see any stored cookies when clicking on the Add to wishlist.
Can give you access if you want to have a look.

**Comment by mnoskov** [comment]
Yes, would be great.

**Comment by fourroses666** [comment]
You have access, login should be emailed.

**Comment by mnoskov** [comment]
Fixed it

**Comment by fourroses666** [comment]
Cool, yea works. :-) 

I wonder, is there a tpl (template) for the Wishlist. 
Would be cool to extend it by showing price, image and adding an "Add to card" button for each item/product.
