### ISSUE TITLE
OnBeforeCartItemAdding

### ISSUE THREAD

**Issue by webber12** [mnoskov/commerce#7]
Не меняет цену. В корзину попадает старая цена почему-то.

```
	case 'OnBeforeCartItemAdding':
		$modx->logEvent(1,1,print_r($item, true),'OnBeforeCartItemAdding1');
		$item['price'] = 180;
		$modx->logEvent(1,1,print_r($item, true),'OnBeforeCartItemAdding2');
		break;
```

в логи попадает сначала старая цена, потом новая - но в корзине все-равно старая. Или там еще какая закавыка?

**Comment by mnoskov** [comment]
Нужно вот так:
```
$params['item']['price'] = 180;
```

**Comment by webber12** [comment]
Да, точно, просто привычно, что это одно и то же :) А в нашем случае после экстракта $params['item'] => $item она доступна, но уже не связана с исходной переменной и не влияет на ее значение.
