### ISSUE TITLE
payOrderByHash

### ISSUE THREAD

**Issue by autogen-travel** [mnoskov/commerce#72]
В методе `payOrderByHash` при отсутствии указанного метода оплаты` $order['fields']['payment_method']` было бы неплохо брать метод по-умолчанию (указанный в настройках плагина).

В моем случае - это вариант с заказом в 1 клик (только имя и телефон).
Можно конечно подставлять в форму скрытое поле метода по умолчанию, но метод по-умолчанию может быть изменяемым (сменили платежную систему, а ссылка на оплату останется старая).

**Comment by mnoskov** [comment]
Мне кажется это не логично. Правильнее будет при создании заказа указывать метод оплаты.
Способ оплаты по умолчанию можно получить так:
```php
ci()->commerce->getSetting('default_payment');
```
либо попробовать получить выбранный способ оплаты - он тоже вернет дефолтный, если ничего не было выбрано:
```php
ci()->commerce->loadProcessor()->getCurrentPayment();
```

**Comment by autogen-travel** [comment]
Ну в настоящий момент получаем ошибку, если метод оплаты не указан в заказе. Вопрос лишь в этом.
