### ISSUE TITLE
Расширение сравнения

### ISSUE THREAD

**Issue by sashabeep** [mnoskov/commerce#74]
В будущем, если возможно, добавить параметр, с помощью которого можно будет передать список id для сравнения, без добавления в список. Возникла задача, например, сравнивать старые и обновленные версии товаров, и страницу с таблицей отправлять по ссылке или крутить в рекламе. Сейчас это делаю с помощью копии сниппета, который принимает список через get-параметр, вместо поиска в корзине сравнения

**Comment by mnoskov** [comment]
[[Comparison? &ids=`1,2,3,4,5`]]
