### ISSUE TITLE
Call to undefined method EvolutionCMS\Database::begin()

### ISSUE THREAD

**Issue by HubraBibik** [mnoskov/commerce#75]
Добрый день.
Evolution CMS 3.0.2, php 7.4.12

При создании и сохранении новой валюты вызывается неопределенный метод begin() в assets/plugins/commerce/src/Module/Controllers/CurrencyController.php : 186, наверное его в 3 версии уже нет.

https://c2n.me/4aU7yqH

**Comment by mnoskov** [comment]
Да, в релиз-кандидатах еще был, а сейчас уже нет.

**Comment by Ser1ous** [comment]
fix https://github.com/evolution-cms/evolution/pull/1859

**Comment by mnoskov** [comment]
fix https://github.com/mnoskov/commerce/commit/6a3c52549e3e076082a8590550d8c8501eea91bb

**Comment by mnoskov** [comment]
@HubraBibik исправлено, можете проверить?

**Comment by HubraBibik** [comment]
> @HubraBibik исправлено, можете проверить?

Теперь ошибки от Evo нет, но ошибка в модуле при Сохранении или Создании "Cannot begin transaction!"
https://c2n.me/4aY8oLE

**Comment by mnoskov** [comment]
https://github.com/mnoskov/commerce/commit/59e59dde3d444475935c5b22c5291ee0b881a2ad

**Comment by HubraBibik** [comment]
> [59e59dd](https://github.com/mnoskov/commerce/commit/59e59dde3d444475935c5b22c5291ee0b881a2ad)

Спасибо.
