### ISSUE TITLE
Параметр &theme в сниппетах не учитывается при получении шаблонов из лексиконов

### ISSUE THREAD

**Issue by Pathologic** [mnoskov/commerce#80]
Можно обойти, задав путь к шаблонам в настройках плагина с учетом theme, но тогда смысл параметра теряется.

**Comment by mnoskov** [comment]
А зачем его там учитывать?

**Comment by Pathologic** [comment]
Ну, хотя бы для того, чтобы соответствовать документации (:

> По умолчанию пустое значение. Можно использовать для темизации корзины, чтобы не указывать все шаблоны по отдельности. Может быть либо префиксом имен файлов, либо именем вложенной папки (тогда в конце нужно указать слэш).

Из-за лексиконов как раз и не получается не указывать все шаблоны по отдельности.

**Comment by mnoskov** [comment]
Так в них же нет ничего для корзины https://github.com/mnoskov/commerce/tree/master/assets/plugins/commerce/templates/front/russian-UTF8 только письма

**Comment by Pathologic** [comment]
Так theme и в Order используется.

**Comment by mnoskov** [comment]
Для лексиконов лучше менять параметр &langDir
