### ISSUE TITLE
Неоднородность имен параметров шаблонов сниппета Cart

### ISSUE THREAD

**Issue by ezhario** [mnoskov/commerce#84]
В сниппете Cart есть параметры:
```
optionsTpl
subtotalsTpl
subtotalsRowTpl
```
в нормальном привычном CamelCase.

И почему-то есть параметры с названиями 
```
ownerTPL
noneTPL
```
которые не соответствуют условному CamelCase. Это вызывает недоумение, при написании параметров руками на автомате пишешь `ownerTpl` и `noneTpl` – и сниппет не рендерит чанки. Есть ли обусловленность какая-то неочевидная, которая требует написания именно `TPL`?

**Comment by mnoskov** [comment]
Cart работает на основе DocLister, параметры ownerTPL и noneTPL оттуда.
