### ISSUE TITLE
Баг ?? события OnBeforeCartItemUpdating

### ISSUE THREAD

**Issue by Aharito** [mnoskov/commerce#85]
Событие OnBeforeCartItemUpdating не отрабатывает перед "обнулением" товара.
То есть, если $params['item']['count'] равен например 3, и шаг тоже 3  или больше, то при нажатии "минус" (data-commerce-action="decrease") событие не отрабатывает.

В общем, событие не работает при $params['item']['count'] <= ШАГ.

**Comment by mnoskov** [comment]
Потому что товар удаляется

**Comment by mnoskov** [comment]
https://github.com/mnoskov/commerce/commit/104dac0d52b449ff2e0909f3a5f650b3ffbf63b3
