### ISSUE TITLE
Выход в свет

### ISSUE THREAD

**Issue by ivan-s-1** [mnoskov/commerce#9]
Привет. Когда ожидать выход в свет законченного решения для массового использования и тестирования ?
Какой нужен донат вам чтоб завершить ваш проект как можно быстрее ? Уж очень понравилась ваша реализация многих функций и удобство.

**Comment by mnoskov** [comment]
Некоторые уже используют :) В принципе модуль готов, есть только некоторые недоделки, в частности редактирование заказов Ну и вопрос в документации.

**Comment by ivan-smirnyagin-1** [comment]
Понял вас, здорово, тогда бы опубликовали в http://modx.im и кошельки для донатов )
